Fix UnicodeEncodeError failures
facebookresearch/muss pull request #18
Opened 2021-08-03 23:35 UTC by lmvasque

Add _encoding='utf-8'_ flag to file streams & strings to avoid "UnicodeEncodeError: 'ascii' codec can't encode character.." errors.

2021-08-04 07:21 UTC, louismartin commented
Thanks for the PR (related to issue https://github.com/facebookresearch/muss/issues/13).
Do you have a minimal file for repro of the error as input to simplify.py?

2021-08-06 17:20 UTC, lmvasque commented
> Thanks for the PR (related to issue #13).
> Do you have a minimal file for repro of the error as input to simplify.py?

Sure, no problem. I do have a failure with the example file in Spanish that is provided with the muss model:

```
python scripts/simplify.py scripts/examples.es --model-name muss_es_mined
File "scripts/simplify.py", line 29, in <module>
print(f'Simplified: {s}')
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 44: ordinal not in range(128)
```

But it can take more time to find the specific lines that failed for the other files that we fixed. I'll let you know if I find another test case.

2021-10-06 10:52 UTC, sadakmed requested changes

2021-10-06 10:52 UTC, sadakmed commented on scripts/simplify.py
> +        c = c.encode('utf-8')
There's no need for encoding here as they will be already encoded with `read_lines` function

2021-10-06 10:52 UTC, sadakmed commented on setup.py
> +with open('requirements.txt', 'r', encoding='utf-8') as f:
no need here, library names are safe from such issues

2021-10-08 10:24 UTC, merged